import {
    booleanTerm,
    booleanType,
    clientImplementation,
    floatTerm,
    floatType,
    functionTermEliminator,
    functionType,
    genericTypeConstructor,
    genericTypeEliminator,
    integerTerm,
    integerType,
    lambdaConstructor,
    largeTypeType,
    library,
    productTermConstructor,
    productTermEliminator,
    productType,
    stringTerm,
    stringType,
    sumTermConstructor,
    sumTermEliminator,
    sumType,
    termBinding,
    termDefinition,
    termReference,
    typeBinding,
    typeDefinition,
    typeReference,
} from "../../defs";

export const strongNodeKinds = [
    "booleanTerm",
    "booleanType",
    "clientImplementation",
    "floatTerm",
    "floatType",
    "functionTermEliminator",
    "functionType",
    "genericTypeConstructor",
    "genericTypeEliminator",
    "integerTerm",
    "integerType",
    "lambdaConstructor",
    "largeTypeType",
    "library",
    "productTermConstructor",
    "productTermEliminator",
    "productType",
    "stringTerm",
    "stringType",
    "sumTermConstructor",
    "sumTermEliminator",
    "sumType",
    "termBinding",
    "termDefinition",
    "termReference",
    "typeBinding",
    "typeDefinition",
    "typeReference",
] as const;

export const strongNodes = {
    booleanTerm,
    booleanType,
    clientImplementation,
    floatTerm,
    floatType,
    functionTermEliminator,
    functionType,
    genericTypeConstructor,
    genericTypeEliminator,
    integerTerm,
    integerType,
    lambdaConstructor,
    largeTypeType,
    library,
    productTermConstructor,
    productTermEliminator,
    productType,
    stringTerm,
    stringType,
    sumTermConstructor,
    sumTermEliminator,
    sumType,
    termBinding,
    termDefinition,
    termReference,
    typeBinding,
    typeDefinition,
    typeReference,
} as const satisfies Record<(typeof strongNodeKinds)[number], unknown>;

export const strongEdges = {
    booleanTerm: booleanTerm.normalizedEdges,
    booleanType: booleanType.normalizedEdges,
    clientImplementation: clientImplementation.normalizedEdges,
    floatTerm: floatTerm.normalizedEdges,
    floatType: floatType.normalizedEdges,
    functionTermEliminator: functionTermEliminator.normalizedEdges,
    functionType: functionType.normalizedEdges,
    genericTypeConstructor: genericTypeConstructor.normalizedEdges,
    genericTypeEliminator: genericTypeEliminator.normalizedEdges,
    integerTerm: integerTerm.normalizedEdges,
    integerType: integerType.normalizedEdges,
    lambdaConstructor: lambdaConstructor.normalizedEdges,
    largeTypeType: largeTypeType.normalizedEdges,
    library: library.normalizedEdges,
    productTermConstructor: productTermConstructor.normalizedEdges,
    productTermEliminator: productTermEliminator.normalizedEdges,
    productType: productType.normalizedEdges,
    stringTerm: stringTerm.normalizedEdges,
    stringType: stringType.normalizedEdges,
    sumTermConstructor: sumTermConstructor.normalizedEdges,
    sumTermEliminator: sumTermEliminator.normalizedEdges,
    sumType: sumType.normalizedEdges,
    termBinding: termBinding.normalizedEdges,
    termDefinition: termDefinition.normalizedEdges,
    termReference: termReference.normalizedEdges,
    typeBinding: typeBinding.normalizedEdges,
    typeDefinition: typeDefinition.normalizedEdges,
    typeReference: typeReference.normalizedEdges,
} as const;
